<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Pluralizer;
use Illuminate\Support\Facades\Session;

class Authenticate extends Middleware
{

    public function handle($request, Closure $next, ...$guards)
    {
        if (!Auth::check()) {
            return redirect()->route('login');
        }
        if (Auth::user()->status === 2) {
            Auth::logout();
            return redirect(route('login'))->withInfo(__("Your account has been deactivated by the administration! For Questions Or Problems Contact Whatsapp +90 850 309 4032    ‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖‖    Hesabınız yönetim tarafından devre dışı bırakıldı! Soru Veya Sorunlar İçin Whatsapp +90 850 309 4032 ile iletişime geçin "));
        }
        $currentIp = request()->ip();
        $isIPv6 = filter_var($currentIp, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6);

        if (Auth::user()->last_ip && !$isIPv6 && Auth::user()->last_ip !== $currentIp) {
            Auth::logout();
            return redirect(route('login'))->withInfo(__("Your IP address is not valid!"));
        }

        if ($request->setLang) {
            if (array_key_exists($request->setLang, Config::get('app.locales'))) {
                Auth::user()->locale = $request->setLang;
                Auth::user()->save();
                $request->session()->put('locale', $request->setLang);
            } else {
                Auth::user()->locale = 'en';
                Auth::user()->save();
                $request->session()->put('locale', 'en');
            }
            return back();
        } else {
            $request->session()->put('locale', Auth::user()->locale);
        }
        App::setlocale(Auth::user()->locale);
        return parent::handle($request, $next, ...$guards); // TODO: Change the autogenerated stub
    }

    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param \Illuminate\Http\Request $request
     * @return string
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('login');
        }
    }
}
